#include<iostream.h>
#include<conio.h>
void main()
{
 clrscr();
 int a,b,c,r;
 cout<<"a:";cin>>a;
 cout<<"b:";cin>>b;
 cout<<"c:";cin>>c;
 r=a>b?a>c?a:c:b>c?b:c;
 cout<<r;
 getch();
}


/*
d print table of x
print factorial of x
d print the following series
  1 4 9 16 . . .100
d print even values between x to y
d print square table from 1 to x in full format
print fibonacci series
0 1 1 2 3 5 8 13 . . .x
*/
